
## Data Types

- In Python, there are different data types: string, integer, and float. 

- Different data types can be contained in a tuple.

### 1. tuples

`Tuples` are an ordered sequences of items, just like `lists.` The main difference between `tuples` and `lists` is that `tuples` cannot be changed (immutable) unlike `lists` which can (mutable).   

`tuples` are collection of different type of objects.

-- empty tuples
```{python}
a = ()
b = tuple()
```


```{python}
## 1. way
a_tuple = (1, 2.5, "string", [3, 4])

b = (1,)
```

**concatenate tuples**

```{python}
b_tuple = ("a", "ab")

a_tuple + b_tuple
```

**slicing**

```{python}
a_tuple[:2]
```


**immutable**

element of a tuple can not be changed 

```{python, eval=F}
a_tuple = (1,2,3,4,5)

a_tuple[5] = "a"

# TypeError: 'tuple' object does not support item assignment
```

**sorted function**

`sorted()` function: We can sort the tuple and assign a new name

`sorted()` function returns list type.

```{python}
a_tuple = (1, 5, 2, 7, 4)

type(sorted(a_tuple))
```

**Nesting**

we can create nested tuples.

```{python}
nested = (1, 2, ("a", "b", "c"), ("ayan", (4, 5)))

nested[2]
```

#### tuple methods

**index method**   
The index method returns the first index at which a value occurs.

```{python}
a = ("a", "b", "c", "d")

a.index("b")
```

**count method**   
The count method returns the number of times a value occurs in a tuple.

```{python}
a = ("a", "b", "c", "d", "a", "b", "c", "d")

a.count("b")
```

**loop thru a tuple**

```{python}
a = ("a", "b", "c", "d", "a", "b", "c", "d")

for item in a:
   print(item)
```


### 2. lists

A list is a sequenced collection of different objects such as integers, strings, and even other lists as well. The address of each element within a list is called an index. An index is used to access and refer to items within a list.

Lists can contain strings, floats, and integers. We can nest other lists, and we can also nest tuples and other data structures. The same indexing conventions apply for nesting:

list are like tuples, ordered sequences.

But lists are mutable.
