## String Operations

-string object are in single quote or double quote

### Indices

**Positive Index**
In python **indices** start with 0
In R **indices** start with 1

**Negative Index**
`-1` corresponds to the last element


```{python}
myname = "Davut Emrah Ayan"

print("Object myname:", myname)
# examples
print(myname[0], 'is the first element of myname object')
print(myname[6], 'is the 6th element of myname object')
print(myname[-1], 'is the last element of myname object')
```

### Slicing

**Full version**

**syntax:** `string_object[from : to : increment]`

```{python}
print("Object:", myname)

print("From 0 index to 5th index, by 1, is", myname[0:5:1])
```

**Short version**

```{python}
print("Object myname:", myname)
print(myname[0:5], "is the first 5 element of the object")
```

**Shorter version**

Numeric string is easier to see.
```{python}
num = "0123456789"
print(num[::2], "every 2 other element")
print(num[::3], "every 3 other element")
print(num[::4], "every 4 other element")
print(num[::5], "every 5 other element")
```

**Length** of an object : `len()`

it is character length or element length
```{python}
len(myname)
```

### Concatenate

```{python}
statement = "KU" + " is the best!"  
statement
```

```{python}
myname[0:5] + " is the best!"
```

**Multiplication with strings**

```{python}
myname[0:6] * 3
```


### Escape 

`\n` : new line
`\t` : tab space

Backward slash '\' is used to escape characters

```{python}
# new line
print("Life \nIs \nGood!")
```

```{python}
# tab space
print("Life\tIs\tGood!")
```

**raw string**
```{python}
print(
  r"Life is good!"
)
```

### Immutable

string objects are immutable, so you can change its any part by indexing

```{python, eval = F}
any_string = "Life is good!"

any_string[5:7] = "was"

# TypeError: 'str' object does not support item assignment
```

### loop thru strings

```{python}
my_txt = "life is good!"

for i in my_txt:
  print(i)
```

```{python}
my_txt = "life is good!"

for i in range(len(my_txt)):
  print(i)
```

### in/not in 

check if a phrase is present in a string

```{python}
my_txt = "life is good!"

print("good" in my_txt)
```

```{python}
if "good" in my_txt:
  print(my_txt)
```


```{python}
if "bad" not in my_txt:
  print("'bad' is not in the text")
```


### Useful Methods used with strings

**uppercase/lowercase**

`upper()` : strings to uppercase
`lower()`
`capitalize()`
```{python}
"Ohh! my life!".upper()
"OHH! MY LIFE!".lower()
"star".capitalize()
```

```{python}
"is it lowercase".islower()
"IS IT UPPERCASE".isupper()
```

**replace method**

`replace()`: to replace part of a string
**syntax:** `string.replace(oldvalue, newvalue, count)`
```{python}
#example
query = '''
select all_columns 
from my_table'''
new_query = query.replace("my_table", "new_table_name")
print(new_query)
```

**strip method**

`strip()` method removes leading or trailing white-space 

```{python}
raw_text = "   my text   "

raw_text.strip()
```

**split method**

`split()` method breaks a string by specified character. 

`split()` method returns list type.

```{python}
raw_text = "banana, apple, cherry"

alist = raw_text.split(",")

alist
```

there are some whitespce in the splitted elements in the list

```{python}
alist[1].strip()
```
