# Pandas Library

run `pip3 install pandas` 
on rstudio terminal or mac terminal or jupyter notebook

## import pandas library

```{python lib1}
import pandas as pd 
pd.set_option('display.max_columns', None)
```


## data creation

Sometimes you may need to create an empty data frame or not empty data frame

```{python}
## empty data frame
df1 = pd.DataFrame()
df1
```

```{python}
df2 = pd.DataFrame({'A' : []})
df2
```

Is df2 empty?

```{python}
df2.empty
```

How to create a sample data frame?

```{python}
df3 = pd.DataFrame({'var1': [1,2,3,4], 'var2': ['a', 'b', 'c', 'd']})
df3
```

### columns

#### column names

How to get the column names?  

--> Column names are stored in `columns` attribute.

```{python}
my_cols = df3.columns
my_cols
```

 - iterating the columns
 
```{python}
for i in df3.columns:
    print(i)
```

- we can put them in a list

```{python}
list(df3.columns)
```

- calling `keys()` function: output is similar to columns attributes

```{python}
df3.keys()
```

- `column.values` method returns an array of index.

```{python}
list(df3.columns.values)
```

Using `tolist()` method with values with given the list of columns. 
```{python}
list(df3.columns.values.tolist())
```

Using `sorted()` method : `sorted()` method will return the list of columns sorted in alphabetical order. 

```{python}
sorted(df3)
```

#### rename

Renaming column names is a standard procedure most of the time. We may need to standardize column names, mostly make them clean.
  
There is a nice link [here.](https://www.statology.org/pandas-rename-columns/)

Lets create a sample data frame

```{python}
df = pd.DataFrame({'A?la': [1,2,3,4],
                    'PYTHON': ['a', 'a', 'a', 'a'],
                    'col 3': ['1','1','b','b']})
df
```

**Method 1: Rename Specific Columns**

```{python}
df.rename(columns = {'PYTHON':'Python'}, inplace = True)

### list column names
list(df)
```

**Method 2: Rename All Columns**

```{python}
new_names = ['new_name1', 'new_name2','new_name3']
df.columns = new_names
list(df)
```

**Method 3: Replace Specific Characters in Columns**

```{python}
### set problematic names
problem_names = ['VAR1$$$', 'var2','Var3###']
df.columns = problem_names

### removing bad characters
df.columns = df.columns.str.replace('$', '', regex = True)
df.columns = df.columns.str.replace('#', '', regex = True)
list(df)
```

**clean column names**

Generally we expect clean columns to be:
  1. short
  2. meaningful
  3. no space
  4. no special character
  5. probably lowercase
  
```{python}
### set problematic names
problem_names = ['VAR  $1', 'var #2','Var ? 3 ']
df.columns = problem_names

## Column names: remove white spaces and convert to lower case
df.columns= df.columns.str.strip()

## Column names: convert to lower case
df.columns = df.columns.str.lower()

## Column names: convert to lower case
df = df.rename(columns = str.lower)

## removing bad characters
df.columns = df.columns.str.replace('$', '', regex = True)
df.columns = df.columns.str.replace('#', '', regex = True)
df.columns = df.columns.str.replace('?', '', regex = True)
df.columns = df.columns.str.replace(' ', '', regex = True)

list(df)
```

- sometimes we need them to be uppercase

```{python}
## Column names: convert to upper case
df.columns = df.columns.str.upper()

list(df)
```



## read data



### csv file

**IBM sample data:** I could not run with "https" because I did not have a certificate installed. So, I go on with "http" and it worked.

```{python data1, eval=FALSE}
data_link = "http://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DS0103EN/labs/data/recipes.csv"

recipes = pd.read_csv(data_link)
```



## Explore Data

```{python}
#recipes.head()
```


### Get the dimensions of the dataframe.

```{python}
#recipes.shape
```








